### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by wojnilowicz** [ActivityWatch/media#3]
Hi, under what license are the files in this repository? I would like to package it for Fedora, so that ActivityWatch is easy installable on that distribution. Could you add a license file to the repository?

The issues is basically the same as at https://github.com/ActivityWatch/aw-server-rust/issues/480 
I understand that that it might be not the most important or interesting thing in the project, but it blocks me from packaging it.

**Comment by ErikBjare** [comment]
There's no code in the repo, so I'm unsure what adding a license would even mean or apply to.

**Comment by wojnilowicz** [comment]
Thanks for your fast reply.

Right, there is no code, but I believe there is some content here, and it could be licensed under Creative Commons license as described at
https://blog.kenkaminesky.com/2017/07/27/how-to-legally-use-copyrighted-images-infographic/

GitHub has a preset only for one CC license i.e. CC0-1.0 but that's not recommended by Fedora.

Fedora allows licenses such as CC-BY, CC-BY-ND, CC-BY-SA (or maybe non-CC if you would like) as seen at
https://docs.fedoraproject.org/en-US/legal/allowed-licenses/#_allowed_content_licenses

Could you pick one from Fedora's site (there are hyperlinks there with required content of the license) and commit to your repository? It would make my task easier.

**Comment by ErikBjare** [comment]
Fixed in https://github.com/ActivityWatch/media/commit/a45151442aa33ed13d4fff8163bbb9b9e7636cee

I ended up going with MPL-2.0 since I understand it the best and think it's the most suitable, given it's the license for the project overall.

**Comment by wojnilowicz** [comment]
> Fixed in [a451514](https://github.com/ActivityWatch/media/commit/a45151442aa33ed13d4fff8163bbb9b9e7636cee)
> 
> I ended up going with MPL-2.0 since I understand it the best and think it's the most suitable, given it's the license for the project overall.

Thanks!
